package udaff.edu.pe.entities;
// Generated 29-oct-2020 13:26:46 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "actividad", catalog = "bd_cetia_v2")
public class Actividad implements java.io.Serializable {

	private Integer idactividad;
	private Date fecha;
	private String titulo;
	private String descripcion;
	private String imagen;
	private Set<PsicAct> psicActs = new HashSet<PsicAct>(0);

	public Actividad() {
	}

	public Actividad(Date fecha, String titulo) {
		this.fecha = fecha;
		this.titulo = titulo;
	}

	public Actividad(Date fecha, String titulo, String descripcion, String imagen, Set<PsicAct> psicActs) {
		this.fecha = fecha;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.psicActs = psicActs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idactividad", unique = true, nullable = false)
	public Integer getIdactividad() {
		return this.idactividad;
	}

	public void setIdactividad(Integer idactividad) {
		this.idactividad = idactividad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", length = 1000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen", length = 100)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividad")
	public Set<PsicAct> getPsicActs() {
		return this.psicActs;
	}

	public void setPsicActs(Set<PsicAct> psicActs) {
		this.psicActs = psicActs;
	}

}
