package udaff.edu.pe.entities;
// Generated 02-nov-2020 23:35:36 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetallereservacionId generated by hbm2java
 */
@Embeddable
public class DetallereservacionId implements java.io.Serializable {

	private int idservicio;
	private Date fecha;
	private Date hora;
	private double precio;
	private String servicio;
	private String nombreusuario;
	private String apellidousuario;
	private Integer dniusuario;

	public DetallereservacionId() {
	}

	public DetallereservacionId(int idservicio, Date fecha, Date hora, double precio, String servicio) {
		this.idservicio = idservicio;
		this.fecha = fecha;
		this.hora = hora;
		this.precio = precio;
		this.servicio = servicio;
	}

	public DetallereservacionId(int idservicio, Date fecha, Date hora, double precio, String servicio,
			String nombreusuario, String apellidousuario, Integer dniusuario) {
		this.idservicio = idservicio;
		this.fecha = fecha;
		this.hora = hora;
		this.precio = precio;
		this.servicio = servicio;
		this.nombreusuario = nombreusuario;
		this.apellidousuario = apellidousuario;
		this.dniusuario = dniusuario;
	}

	@Column(name = "idservicio", nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "servicio", nullable = false, length = 100)
	public String getServicio() {
		return this.servicio;
	}

	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	@Column(name = "nombreusuario", length = 50)
	public String getNombreusuario() {
		return this.nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	@Column(name = "apellidousuario", length = 50)
	public String getApellidousuario() {
		return this.apellidousuario;
	}

	public void setApellidousuario(String apellidousuario) {
		this.apellidousuario = apellidousuario;
	}

	@Column(name = "dniusuario")
	public Integer getDniusuario() {
		return this.dniusuario;
	}

	public void setDniusuario(Integer dniusuario) {
		this.dniusuario = dniusuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallereservacionId))
			return false;
		DetallereservacionId castOther = (DetallereservacionId) other;

		return (this.getIdservicio() == castOther.getIdservicio())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora().equals(castOther.getHora())))
				&& (this.getPrecio() == castOther.getPrecio())
				&& ((this.getServicio() == castOther.getServicio()) || (this.getServicio() != null
						&& castOther.getServicio() != null && this.getServicio().equals(castOther.getServicio())))
				&& ((this.getNombreusuario() == castOther.getNombreusuario())
						|| (this.getNombreusuario() != null && castOther.getNombreusuario() != null
								&& this.getNombreusuario().equals(castOther.getNombreusuario())))
				&& ((this.getApellidousuario() == castOther.getApellidousuario())
						|| (this.getApellidousuario() != null && castOther.getApellidousuario() != null
								&& this.getApellidousuario().equals(castOther.getApellidousuario())))
				&& ((this.getDniusuario() == castOther.getDniusuario())
						|| (this.getDniusuario() != null && castOther.getDniusuario() != null
								&& this.getDniusuario().equals(castOther.getDniusuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdservicio();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result + (int) this.getPrecio();
		result = 37 * result + (getServicio() == null ? 0 : this.getServicio().hashCode());
		result = 37 * result + (getNombreusuario() == null ? 0 : this.getNombreusuario().hashCode());
		result = 37 * result + (getApellidousuario() == null ? 0 : this.getApellidousuario().hashCode());
		result = 37 * result + (getDniusuario() == null ? 0 : this.getDniusuario().hashCode());
		return result;
	}

}
