package udaff.edu.pe.entities;
// Generated 14 nov. 2020 18:02:31 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "bd_cetia_v2")
public class Login implements java.io.Serializable {

	private LoginId id;

	public Login() {
	}

	public Login(LoginId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "userCuenta", column = @Column(name = "user_cuenta", nullable = false, length = 50)),
			@AttributeOverride(name = "userClave", column = @Column(name = "user_clave", nullable = false, length = 50)),
			@AttributeOverride(name = "userRol", column = @Column(name = "user_rol", nullable = false)) })
	public LoginId getId() {
		return this.id;
	}

	public void setId(LoginId id) {
		this.id = id;
	}

}
