package udaff.edu.pe.entities;
// Generated 15 nov. 2020 0:24:20 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Nuestroservicio generated by hbm2java
 */
@Entity
@Table(name = "nuestroservicio", catalog = "bd_cetia_v2")
public class Nuestroservicio implements java.io.Serializable {

	private NuestroservicioId id;

	public Nuestroservicio() {
	}

	public Nuestroservicio(NuestroservicioId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codigo", column = @Column(name = "codigo", nullable = false)),
			@AttributeOverride(name = "titulo", column = @Column(name = "titulo", nullable = false, length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", length = 1000)),
			@AttributeOverride(name = "imagen", column = @Column(name = "imagen", length = 100)),
			@AttributeOverride(name = "precio", column = @Column(name = "precio", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", nullable = false, length = 50)) })
	public NuestroservicioId getId() {
		return this.id;
	}

	public void setId(NuestroservicioId id) {
		this.id = id;
	}

}
