package udaff.edu.pe.entities;
// Generated 02-nov-2020 22:55:50 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NuestroEquipoId generated by hbm2java
 */
@Embeddable
public class NuestroEquipoId implements java.io.Serializable {

	private String nombre;
	private String apellido;
	private String especialidad;
	private String foto;

	public NuestroEquipoId() {
	}

	public NuestroEquipoId(String especialidad) {
		this.especialidad = especialidad;
	}

	public NuestroEquipoId(String nombre, String apellido, String especialidad, String foto) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.especialidad = especialidad;
		this.foto = foto;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "especialidad", nullable = false, length = 50)
	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	@Column(name = "foto", length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NuestroEquipoId))
			return false;
		NuestroEquipoId castOther = (NuestroEquipoId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
				&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getEspecialidad() == castOther.getEspecialidad())
						|| (this.getEspecialidad() != null && castOther.getEspecialidad() != null
								&& this.getEspecialidad().equals(castOther.getEspecialidad())))
				&& ((this.getFoto() == castOther.getFoto()) || (this.getFoto() != null && castOther.getFoto() != null
						&& this.getFoto().equals(castOther.getFoto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getEspecialidad() == null ? 0 : this.getEspecialidad().hashCode());
		result = 37 * result + (getFoto() == null ? 0 : this.getFoto().hashCode());
		return result;
	}

}
