package udaff.edu.pe.entities;
// Generated 02-nov-2020 19:08:29 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PsicServ generated by hbm2java
 */
@Entity
@Table(name = "psic_serv", catalog = "bd_cetia_v2")
public class PsicServ implements java.io.Serializable {

	private Integer idpsicServ;
	private Psicologo psicologo;
	private Servicio servicio;

	public PsicServ() {
	}

	public PsicServ(Psicologo psicologo, Servicio servicio) {
		this.psicologo = psicologo;
		this.servicio = servicio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpsic_serv", unique = true, nullable = false)
	public Integer getIdpsicServ() {
		return this.idpsicServ;
	}

	public void setIdpsicServ(Integer idpsicServ) {
		this.idpsicServ = idpsicServ;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Psicologo getPsicologo() {
		return this.psicologo;
	}

	public void setPsicologo(Psicologo psicologo) {
		this.psicologo = psicologo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idservicio", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

}
