package udaff.edu.pe.entities;
// Generated 02-nov-2020 19:08:29 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PsicAct generated by hbm2java
 */
@Entity
@Table(name = "psic_act", catalog = "bd_cetia_v2")
public class PsicAct implements java.io.Serializable {

	private Integer idpsicAct;
	private Actividad actividad;
	private Psicologo psicologo;

	public PsicAct() {
	}

	public PsicAct(Actividad actividad, Psicologo psicologo) {
		this.actividad = actividad;
		this.psicologo = psicologo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpsic_act", unique = true, nullable = false)
	public Integer getIdpsicAct() {
		return this.idpsicAct;
	}

	public void setIdpsicAct(Integer idpsicAct) {
		this.idpsicAct = idpsicAct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idactividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Psicologo getPsicologo() {
		return this.psicologo;
	}

	public void setPsicologo(Psicologo psicologo) {
		this.psicologo = psicologo;
	}

}
