package udaff.edu.pe.entities;
// Generated 29-oct-2020 13:26:46 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PsicPubl generated by hbm2java
 */
@Entity
@Table(name = "psic_publ", catalog = "bd_cetia_v2")
public class PsicPubl implements java.io.Serializable {

	private int idpsicPubli;
	private Psicologo psicologo;
	private Publicacion publicacion;

	public PsicPubl() {
	}

	public PsicPubl(int idpsicPubli, Psicologo psicologo, Publicacion publicacion) {
		this.idpsicPubli = idpsicPubli;
		this.psicologo = psicologo;
		this.publicacion = publicacion;
	}

	@Id

	@Column(name = "idpsic_publi", unique = true, nullable = false)
	public int getIdpsicPubli() {
		return this.idpsicPubli;
	}

	public void setIdpsicPubli(int idpsicPubli) {
		this.idpsicPubli = idpsicPubli;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Psicologo getPsicologo() {
		return this.psicologo;
	}

	public void setPsicologo(Psicologo psicologo) {
		this.psicologo = psicologo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpublicacion", nullable = false)
	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

}
