package udaff.edu.pe.entities;
// Generated 29-oct-2020 13:26:46 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PsicAct generated by hbm2java
 */
@Entity
@Table(name = "psic_act", catalog = "bd_cetia_v2")
public class PsicAct implements java.io.Serializable {

	private int idpsicAct;
	private Actividad actividad;
	private Psicologo psicologo;

	public PsicAct() {
	}

	public PsicAct(int idpsicAct, Actividad actividad, Psicologo psicologo) {
		this.idpsicAct = idpsicAct;
		this.actividad = actividad;
		this.psicologo = psicologo;
	}

	@Id

	@Column(name = "idpsic_act", unique = true, nullable = false)
	public int getIdpsicAct() {
		return this.idpsicAct;
	}

	public void setIdpsicAct(int idpsicAct) {
		this.idpsicAct = idpsicAct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idactividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Psicologo getPsicologo() {
		return this.psicologo;
	}

	public void setPsicologo(Psicologo psicologo) {
		this.psicologo = psicologo;
	}

}
