package udaff.edu.pe.entities;
// Generated 02-nov-2020 22:55:50 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicacion generated by hbm2java
 */
@Entity
@Table(name = "publicacion", catalog = "bd_cetia_v2")
public class Publicacion implements java.io.Serializable {

	private int idpublicacion;
	private Psicologo psicologo;
	private TipoPublicacion tipoPublicacion;
	private String titulo;
	private Date fecha;
	private Date hora;
	private String descripcion;
	private String imagen;

	public Publicacion() {
	}

	public Publicacion(int idpublicacion, Psicologo psicologo, TipoPublicacion tipoPublicacion, String titulo,
			Date fecha, Date hora, String imagen) {
		this.idpublicacion = idpublicacion;
		this.psicologo = psicologo;
		this.tipoPublicacion = tipoPublicacion;
		this.titulo = titulo;
		this.fecha = fecha;
		this.hora = hora;
		this.imagen = imagen;
	}

	public Publicacion(int idpublicacion, Psicologo psicologo, TipoPublicacion tipoPublicacion, String titulo,
			Date fecha, Date hora, String descripcion, String imagen) {
		this.idpublicacion = idpublicacion;
		this.psicologo = psicologo;
		this.tipoPublicacion = tipoPublicacion;
		this.titulo = titulo;
		this.fecha = fecha;
		this.hora = hora;
		this.descripcion = descripcion;
		this.imagen = imagen;
	}

	@Id

	@Column(name = "idpublicacion", unique = true, nullable = false)
	public int getIdpublicacion() {
		return this.idpublicacion;
	}

	public void setIdpublicacion(int idpublicacion) {
		this.idpublicacion = idpublicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Psicologo getPsicologo() {
		return this.psicologo;
	}

	public void setPsicologo(Psicologo psicologo) {
		this.psicologo = psicologo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipopublicacion", nullable = false)
	public TipoPublicacion getTipoPublicacion() {
		return this.tipoPublicacion;
	}

	public void setTipoPublicacion(TipoPublicacion tipoPublicacion) {
		this.tipoPublicacion = tipoPublicacion;
	}

	@Column(name = "titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "descripcion", length = 1000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen", nullable = false, length = 200)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

}
