package udaff.edu.pe.entities;
// Generated 29-oct-2020 13:26:46 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicacion generated by hbm2java
 */
@Entity
@Table(name = "publicacion", catalog = "bd_cetia_v2")
public class Publicacion implements java.io.Serializable {

	private Integer idpublicacion;
	private TipoPublicacion tipoPublicacion;
	private String titulo;
	private Date fecha;
	private String descripcion;
	private Set<PsicPubl> psicPubls = new HashSet<PsicPubl>(0);

	public Publicacion() {
	}

	public Publicacion(TipoPublicacion tipoPublicacion, String titulo, Date fecha) {
		this.tipoPublicacion = tipoPublicacion;
		this.titulo = titulo;
		this.fecha = fecha;
	}

	public Publicacion(TipoPublicacion tipoPublicacion, String titulo, Date fecha, String descripcion,
			Set<PsicPubl> psicPubls) {
		this.tipoPublicacion = tipoPublicacion;
		this.titulo = titulo;
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.psicPubls = psicPubls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpublicacion", unique = true, nullable = false)
	public Integer getIdpublicacion() {
		return this.idpublicacion;
	}

	public void setIdpublicacion(Integer idpublicacion) {
		this.idpublicacion = idpublicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipopublicacion", nullable = false)
	public TipoPublicacion getTipoPublicacion() {
		return this.tipoPublicacion;
	}

	public void setTipoPublicacion(TipoPublicacion tipoPublicacion) {
		this.tipoPublicacion = tipoPublicacion;
	}

	@Column(name = "titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "descripcion", length = 1000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publicacion")
	public Set<PsicPubl> getPsicPubls() {
		return this.psicPubls;
	}

	public void setPsicPubls(Set<PsicPubl> psicPubls) {
		this.psicPubls = psicPubls;
	}

}
