package udaff.edu.pe.entities;
// Generated 29-oct-2020 13:26:46 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservacion generated by hbm2java
 */
@Entity
@Table(name = "reservacion", catalog = "bd_cetia_v2")
public class Reservacion implements java.io.Serializable {

	private int idreservacion;
	private Date fecha;
	private Date hora;
	private double precio;
	private Boolean atencion;
	private int idservicio;
	private Set<UsuReser> usuResers = new HashSet<UsuReser>(0);

	public Reservacion() {
	}

	public Reservacion(int idreservacion, Date fecha, Date hora, double precio, int idservicio) {
		this.idreservacion = idreservacion;
		this.fecha = fecha;
		this.hora = hora;
		this.precio = precio;
		this.idservicio = idservicio;
	}

	public Reservacion(int idreservacion, Date fecha, Date hora, double precio, Boolean atencion, int idservicio,
			Set<UsuReser> usuResers) {
		this.idreservacion = idreservacion;
		this.fecha = fecha;
		this.hora = hora;
		this.precio = precio;
		this.atencion = atencion;
		this.idservicio = idservicio;
		this.usuResers = usuResers;
	}

	@Id

	@Column(name = "idreservacion", unique = true, nullable = false)
	public int getIdreservacion() {
		return this.idreservacion;
	}

	public void setIdreservacion(int idreservacion) {
		this.idreservacion = idreservacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "atencion")
	public Boolean getAtencion() {
		return this.atencion;
	}

	public void setAtencion(Boolean atencion) {
		this.atencion = atencion;
	}

	@Column(name = "idservicio", nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservacion")
	public Set<UsuReser> getUsuResers() {
		return this.usuResers;
	}

	public void setUsuResers(Set<UsuReser> usuResers) {
		this.usuResers = usuResers;
	}

}
