package udaff.edu.pe.entities;
// Generated 14 nov. 2020 20:21:29 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservacion generated by hbm2java
 */
@Entity
@Table(name = "reservacion", catalog = "bd_cetia_v2")
public class Reservacion implements java.io.Serializable {

	private Integer idreservacion;
	private Servicio servicio;
	private Usuario usuario;
	private Date fecha;
	private Date hora;
	private double precio;
	private String atencion;

	public Reservacion() {
	}

	public Reservacion(Servicio servicio, Usuario usuario, Date fecha, Date hora, double precio) {
		this.servicio = servicio;
		this.usuario = usuario;
		this.fecha = fecha;
		this.hora = hora;
		this.precio = precio;
	}

	public Reservacion(Servicio servicio, Usuario usuario, Date fecha, Date hora, double precio, String atencion) {
		this.servicio = servicio;
		this.usuario = usuario;
		this.fecha = fecha;
		this.hora = hora;
		this.precio = precio;
		this.atencion = atencion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idreservacion", unique = true, nullable = false)
	public Integer getIdreservacion() {
		return this.idreservacion;
	}

	public void setIdreservacion(Integer idreservacion) {
		this.idreservacion = idreservacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idservicio", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", nullable = false, length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "atencion", length = 30)
	public String getAtencion() {
		return this.atencion;
	}

	public void setAtencion(String atencion) {
		this.atencion = atencion;
	}

}
