package udaff.edu.pe.entities;
// Generated 29-oct-2020 13:26:46 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", catalog = "bd_cetia_v2")
public class Servicio implements java.io.Serializable {

	private int idservicio;
	private String titulo;
	private String descripcion;
	private String imagen;
	private double precio;
	private Set<PsicServ> psicServs = new HashSet<PsicServ>(0);

	public Servicio() {
	}

	public Servicio(int idservicio, String titulo, double precio) {
		this.idservicio = idservicio;
		this.titulo = titulo;
		this.precio = precio;
	}

	public Servicio(int idservicio, String titulo, String descripcion, String imagen, double precio,
			Set<PsicServ> psicServs) {
		this.idservicio = idservicio;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.precio = precio;
		this.psicServs = psicServs;
	}

	@Id

	@Column(name = "idservicio", unique = true, nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@Column(name = "titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", length = 1000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen", length = 100)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<PsicServ> getPsicServs() {
		return this.psicServs;
	}

	public void setPsicServs(Set<PsicServ> psicServs) {
		this.psicServs = psicServs;
	}

}
