package udaff.edu.pe.entities;
// Generated 14 nov. 2020 20:21:29 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VistaPublicacion generated by hbm2java
 */
@Entity
@Table(name = "vista_publicacion", catalog = "bd_cetia_v2")
public class VistaPublicacion implements java.io.Serializable {

	private VistaPublicacionId id;

	public VistaPublicacion() {
	}

	public VistaPublicacion(VistaPublicacionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 50)),
			@AttributeOverride(name = "apellido", column = @Column(name = "apellido", length = 50)),
			@AttributeOverride(name = "especialidad", column = @Column(name = "especialidad", nullable = false, length = 50)),
			@AttributeOverride(name = "imagen", column = @Column(name = "imagen", length = 100)) })
	public VistaPublicacionId getId() {
		return this.id;
	}

	public void setId(VistaPublicacionId id) {
		this.id = id;
	}

}
