package udaff.edu.pe.entities;
// Generated 15 nov. 2020 0:24:20 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VistaPublicacionId generated by hbm2java
 */
@Embeddable
public class VistaPublicacionId implements java.io.Serializable {

	private String nombre;
	private String apellido;
	private String especialidad;
	private String imagen;

	public VistaPublicacionId() {
	}

	public VistaPublicacionId(String especialidad) {
		this.especialidad = especialidad;
	}

	public VistaPublicacionId(String nombre, String apellido, String especialidad, String imagen) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.especialidad = especialidad;
		this.imagen = imagen;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "especialidad", nullable = false, length = 50)
	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	@Column(name = "imagen", length = 100)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaPublicacionId))
			return false;
		VistaPublicacionId castOther = (VistaPublicacionId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
				&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getEspecialidad() == castOther.getEspecialidad())
						|| (this.getEspecialidad() != null && castOther.getEspecialidad() != null
								&& this.getEspecialidad().equals(castOther.getEspecialidad())))
				&& ((this.getImagen() == castOther.getImagen()) || (this.getImagen() != null
						&& castOther.getImagen() != null && this.getImagen().equals(castOther.getImagen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getEspecialidad() == null ? 0 : this.getEspecialidad().hashCode());
		result = 37 * result + (getImagen() == null ? 0 : this.getImagen().hashCode());
		return result;
	}

}
